'BF2SB v2.2.2 (SB3) Options
'By HTV04

'NOTE: These options are intended for
'advanced users who want to alter how
'brainf**k code is converted.

'NOTE: Descriptions for these options can be
'found in the README.

'--Options--

'-Brainf**k Code Options-
VAR OPTIMIZE=1
VAR MEMSIZE=30000
VAR BITWIDTH=8
VAR SIGNEDINT=0

'--

'-Converted Code Options-
VAR SBCOMMENT=1
VAR SBOPTIMIZE=1
VAR SBMEMOF=0
VAR SBCHR13=1
VAR SBINPUT=1
VAR SBINPUT$=""
VAR SBINPUTEOF=2
VAR SBWAIT=0
VAR SBWAITCNT=1
VAR SBINDENT=1
VAR SBNEWLINES=1

'--

'----

